CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PEOPLE(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    ACTIVE BOOLEAN NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    EMAIL VARCHAR(70) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(70) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_PERSON_ID PRIMARY KEY(ID)
);