CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE ADDRESSES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    OWNER_ID UUID NOT NULL,
    ADDRESS VARCHAR(120) NOT NULL,
    PUBLIC_PLACE VARCHAR(30) NOT NULL,
    NEIGHBORHOOD VARCHAR(120) NOT NULL,
    NUMBER INTEGER NOT NULL,
    COUNTY VARCHAR(120) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(120) NOT NULL,
    POSTAL_CODE VARCHAR(12) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
      CONSTRAINT PK_ADDRESS_ID PRIMARY KEY(ID),
    CONSTRAINT FK_ADDRESS_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES PEOPLE (id)
    MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX ADDRESSES_OWNER_ID ON PUBLIC.ADDRESSES USING BTREE(OWNER_ID);