CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS DOCUMENTS(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    OWNER_ID UUID NOT NULL,
    NUMBER VARCHAR(20) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_DOCUMENT_ID PRIMARY KEY(ID),
    CONSTRAINT FK_DOCUMENT_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES PEOPLE (id)
    MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX DOCUMENTS_OWNER_ID ON PUBLIC.DOCUMENTS USING BTREE(OWNER_ID);