CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PHONES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    OWNER_ID UUID NOT NULL,
    DDD VARCHAR(3) NOT NULL,
    DDI VARCHAR(3) NOT NULL,
    NUMBER VARCHAR(9) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_PHONE_ID PRIMARY KEY(ID),
    CONSTRAINT FK_PHONE_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES PEOPLE (id)
    MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX PHONES_OWNER_ID ON PUBLIC.PHONES USING BTREE(OWNER_ID);